### ISSUE TITLE
Spreadsheet

### ISSUE THREAD

**Issue by matkoniecz** [goldfndr/StreetCompleteJSON#1]
I would add also spreadsheet that was used to make json file to make future updates easier.

**Comment by rugk** [comment]
…as a (platform-agnostic) CSV, preferably, as this is easier to edit with any spreadsheet editor. (and you can read it in plain-text/on GitHub).

**Comment by matkoniecz** [comment]
I am pretty sure that in CSV export any formulas are lost as values are exported.

**Comment by rugk** [comment]
It seems to work… 😄 (at least the formula is there)

**Comment by goldfndr** [comment]
One concern is that the formula doesn't survive intact on GitHub's rendering of the file. I don't know why, but it's removing the space after the comma in the last fields. The CSV as rendered in Excel matches.

**Comment by rugk** [comment]
Yeah, you cannot do anything with the GitHub table anyway, it does not do anything with formulas, so it's all ok.
