### ISSUE TITLE
Keys: "(exclusion)" alternatives?

### ISSUE THREAD

**Issue by goldfndr** [goldfndr/StreetCompleteJSON#12]
While a tag (e.g. access=private) being marked as an exclusion seems fine, for a key (e.g. access) it seems a bit less clear.

For example, in the Parking Access quest, the query includes `(!access or access=unknown)`. It seems odd in the taginfo table to claim to exclude values of access while including one particular value.

Unfortunately, the antonyms of "required" and "mandatory" tend toward "optional". I toyed with "not present" but that didn't seem quite right.

Would "absent" or something else be more sensible? Thoughts?

**Comment by rugk** [comment]
> It seems odd in the taginfo table to claim to exclude values of access while including one particular value.

The example you've stated excludes the quest from all tags with `access` set or access to to `unknown`, which obviously has no informnation value. So basically the quest is just including things without any (useful) access information.

**Comment by goldfndr** [comment]
I'm not criticizing the query – including `unknown` values is preferable to me. There was some other query I commented on where I thought unverifiable values should be replaced but was shot down. 

This issue is only about how I have taginfo currently presenting the tags.

**Comment by rugk** [comment]
Yeah, so how is it done currently? Do you have any screenshot of what "seems odd"? I don't quite understand the problem here.

**Comment by goldfndr** [comment]
The only instances are the Parking Access and Playground Access, the latter of which actually has a bug (it's showing access=unknown as exclusion).

As the access=* and access=unknown can't be easily shown on the same screen in taginfo, I'm going to close this. If anyone wants to suggest alternatives to "(exclusion)", I'd be happy to reopen this.
