### ISSUE TITLE
Cycleway quest query: junction=roundabout?

### ISSUE THREAD

**Issue by goldfndr** [goldfndr/StreetCompleteJSON#14]
In https://github.com/westnordost/StreetComplete/commit/277815e73118ead8c4af35c6455d9c18b33c2cb7#diff-b3a17b0a0a883ad82058bbe2dd23add2, the `junction=roundabout` portion of the query (among others) was moved from AddCycleway.java to AddCyclewayForm.java.

Should it have a "Cycleway quest query" or "Cycleway quest query (exclusion)" or (something else) entry in this repository's taginfo.json?

**Comment by westnordost** [comment]
So basically, the `junction=roundabout` tag and the others your see there are not anymore used to determine if the quest is shown at all or not, but to modify how/what is shown in the form: If it is a oneway (and a roundabout is implicitly a oneway), only one side (the right side in countries with right-hand traffic) of the street is shown in the form.

Looking at the element to adapt the form is used in a couple of different quest forms. Aside from simple adaptions in wording, it is also done here:
- AddRoadSurfaceForm and AddPathSurfaceForm show different top items based on the highway value
- AddMaxSpeedForm only shows the "Is a living street" answer if the road is residential or unclassified. Only shows the slow-zone answer-option if the road is a residential, unclassified or tertiary

All in all, I would say this usage of OSM tags is not noteworthy.

**Comment by goldfndr** [comment]
>a roundabout is implicitly a oneway

Then I'm thinking the isOneWay function might not be correct in a useful sense, since it only tests for the oneway tag and not junction=roundabout.

>Aside from simple adaptions in wording

I do have entries for tags that change the wording (just seek "wording" in the json). So I'm thinking that there's a precedent for adding junction=roundabout to the list. But I think I might change the word "wording" to "presentation"; I'll give myself some time to think of a better word (feel free, anyone, to suggest).

**Comment by westnordost** [comment]
Only if a roundabout with a bicycle contraflow lane is something that could actually happen in reality.

Am 23. August 2018 02:05:12 MESZ schrieb Richard Finegold <notifications@github.com>:
>>a roundabout is implicitly a oneway
>
>Then I'm thinking the isOneWay function might not be correct in a
>useful sense, since it only tests for the oneway tag and not
>junction=roundabout.
>
>>Aside from simple adaptions in wording
>
>I do have entries for tags that change the wording (just seek "wording"
>in the json). So I'm thinking that there's a precedent for adding
>junction=roundabout to the list. But I think I might change the word
>"wording" to "presentation"; I'll give myself some time to think of a
>better word (feel free, anyone, to suggest).

**Comment by goldfndr** [comment]
Admittedly, a query of `nwr[junction=roundabout]["oneway:bicycle"="-1"]` gets no results.

And a query of `
  nwr[junction=roundabout]["cycleway"]["oneway:bicycle"="no"]({{bbox}});
  nwr[junction=roundabout]["cycleway:left"]["oneway:bicycle"="no"]({{bbox}});
  nwr[junction=roundabout]["cycleway:right"]["oneway:bicycle"="no"]({{bbox}});
  nwr[junction=roundabout]["cycleway:both"]["oneway:bicycle"="no"]({{bbox}});
` doesn't have any cycleway*:lanes instances.
