### ISSUE TITLE
level, level:ref, addr:floor

### ISSUE THREAD

**Issue by westnordost** [goldfndr/StreetCompleteJSON#16]
Streetcomplete now uses these tags to display it on the quest form (for any quest). See
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractQuestAnswerFragment.kt#L162-L175

**Comment by goldfndr** [comment]
I strongly suspect that some of the referenced code

```kotlin
        val tunnel = tags["tunnel"]
        if(tunnel != null && tunnel == "yes" || tags["location"] == "underground") {
```

can be reduced to
```kotlin
        if(tags["tunnel"] == "yes" || tags["location"] == "underground") {
```
