### ISSUE TITLE
License

### ISSUE THREAD

**Issue by matkoniecz** [goldfndr/StreetCompleteJSON#2]
I would also add a license file for a clarity.

**Comment by rugk** [comment]
LOL, why does not think @westnordost so?

**Comment by goldfndr** [comment]
Given that some countries have a [*sui generis* database right](https://en.wikipedia.org/wiki/Sui_generis_database_right), yes, it looks like I do need to declare a license. I think the only creative aspects were

* Choosing which tags to include and which to exclude
* Ordering, usually by order found in the queries and `changes.add`/`changes.modify` calls

I suppose the formula I used to put it all together has some creativity (though not much). I'll admit that before I was using a bunch of IF()s for the object types, but I've switched to an OFFSET(MATCH()) which is much shorter. Still pretty trivial.
