### ISSUE TITLE
"This table shows all projects known to taginfo that use OSM tags in some way."

### ISSUE THREAD

**Issue by matkoniecz** [goldfndr/StreetCompleteJSON#3]
I wonder whatever it should also include administrative boundaries tags (StreetComplete is using OSM-derived country boundaries for variety of things - disabling/enabling quests, country specific interface)...

**Comment by westnordost** [comment]
> StreetComplete is using OSM-derived country boundaries for variety of things

Not really true. They are derived from JOSM metadata, which is only indirectly drawn from OSM data. Indirectly enough that I would not see a direct connection to the tags.

**Comment by matkoniecz** [comment]
I know about indirection, but I thought that it would be enough to count.
