### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by ENT8R** [goldfndr/StreetCompleteJSON#4]
You name yourself as a contact person here:
https://github.com/goldfndr/StreetCompleteJSON/blob/9d8e962154abb34cb4a0ba442ec973558fa69010/taginfo.json#L9
Maybe it might be better to write down the contact information of @westnordost as he is the maintainer of SC...

**Comment by westnordost** [comment]
But not the maintainer of the taginfo.json. Don't know which contact info should be shown there though.

**Comment by goldfndr** [comment]
[The project file description](https://wiki.openstreetmap.org/wiki/Taginfo/Projects) is somewhat ambiguous. It specifies that they are *needed for taginfo maintainer* but doesn't clarify whether that's:

* Information the taginfo project's/site's maintainer needs (which would probably be the project's maintainer), or
* The JSON file's maintainer, which might be labeled a taginfo maintainer.

I'll open an issue [there](https://github.com/taginfo/taginfo-projects).

**Comment by goldfndr** [comment]
I got an answer. What I have (me) is correct.
