### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by rugk** [goldfndr/StreetCompleteJSON#9]
v6 has some new quests https://github.com/westnordost/StreetComplete/releases/tag/v6.0-beta1 and I guess also older versions are not yet included here.

**Comment by goldfndr** [comment]
True.

I'll definitely add the ones listed at https://wiki.openstreetmap.org/wiki/StreetComplete/Quests. I added them here in the same order in which they appear in the wiki's table, but I'm unclear on what method you use to sort the table (i.e. how you decide where to insert each row) so I'm a bit hesitant about adding the ones not in the table.

If you do have wiki sorting/insertion guidance, I'm hopeful that you can add it to StreetComplete's CONTRIBUTING.md or as a `<!-- comment -->` in the wiki. If I somehow missed it, please point it out.

**Comment by rugk** [comment]
How I sort the wiki: I try to group the ones together, which are somewhat related (or public transport etc).

As for your use case though, would not it help to click the "Since version" column, so it sorts by the SC version? At least for adding new quests.
Apart from that, you can of course always look at version history.

**Comment by goldfndr** [comment]
Updated to version 6.
